const restdata = [
  {
    id: 1,
    name: "Tasty Delights",
    rating: 4.5,
    etp: "Casual Dining",
    menu: ["Pasta Alfredo", "Grilled Chicken", "Vegetable Biryani", "Chocolate Cake"],
    cost_for_two: 350,
    veg_or_nonveg: "Vegetarian",
    tags: ["Italian", "Indian", "Desserts"],
    image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/e33e1d3ba7d6b2bb0d45e1001b731fcf",
  },
  {
    id: 2,
    name: "Spice Haven",
    rating: 4.2,
    etp: "Fine Dining",
    menu: ["Paneer Tikka", "Butter Chicken", "Bhuna Gosht", "Gulab Jamun"],
    cost_for_two: 400,
    veg_or_nonveg: "Non-Vegetarian",
    tags: ["Indian", "Mughlai", "Desserts"],
    image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/079d1a1551619115a435f9b557222464",
  },
  {
    id: 3,
    name: "Green Bites",
    rating: 4.0,
    etp: "Healthy Eating",
    menu: ["Quinoa Salad", "Grilled Salmon", "Vegetable Stir-Fry", "Fruit Smoothie"],
    cost_for_two: 300,
    veg_or_nonveg: "Vegetarian",
    tags: ["Healthy", "Salads", "Smoothies"],
    image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/ff0747ae3755d4ed49a4d7c0c2d8a2d4",
  },
  {
    id: 4,
    name: "Sushi Palace",
    rating: 4.7,
    etp: "Japanese Cuisine",
    menu: ["Sushi Platter", "Teriyaki Chicken", "Miso Soup", "Green Tea Ice Cream"],
    cost_for_two: 500,
    veg_or_nonveg: "Non-Vegetarian",
    tags: ["Japanese", "Sushi", "Soups"],
    image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/ambej9g4jx7g7drkigpt",
  },
  {
    id: 5,
    name: "Mediterranean Flavors",
    rating: 4.4,
    etp: "Mediterranean Cuisine",
    menu: ["Hummus Platter", "Falafel Wrap", "Moussaka", "Baklava"],
    cost_for_two: 350,
    veg_or_nonveg: "Vegetarian",
    tags: ["Mediterranean", "Middle Eastern", "Desserts"],
    image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/hjv1ytk3ibolyt2cxr30",
  },
  {
    id: 6,
    name: "Burger Bliss",
    rating: 4.1,
    etp: "Fast Food",
    menu: ["Classic Burger", "Chicken Sandwich", "Sweet Potato Fries", "Milkshake"],
    cost_for_two: 250,
    veg_or_nonveg: "Non-Vegetarian",
    tags: ["Burgers", "Fast Food", "Milkshakes"],
    image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/dzpkrfcm1szh0azuarof",
  },
  {
    id: 7,
    name: "Café Serenity",
    rating: 4.3,
    etp: "Coffee Shop",
    menu: ["Espresso", "Cappuccino", "Avocado Toast", "Cheesecake"],
    cost_for_two: 300,
    veg_or_nonveg: "Vegetarian",
    tags: ["Coffee", "Breakfast", "Desserts"],
    image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/405645b3118d83e89db4c65361e43733",
  },
  {
    id: 8,
    name: "Thai Spice House",
    rating: 4.6,
    etp: "Thai Cuisine",
    menu: ["Tom Yum Soup", "Pad Thai Noodles", "Green Curry", "Mango Sticky Rice"],
    cost_for_two: 450,
    veg_or_nonveg: "Non-Vegetarian",
    tags: ["Thai", "Noodles", "Curry"],
    image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/e33e1d3ba7d6b2bb0d45e1001b731fcf",
  },
  {
    id: 9,
    name: "Pizza Paradise",
    rating: 4.8,
    etp: "Pizzeria",
    menu: ["Margherita Pizza", "Pepperoni Pizza", "Caprese Salad", "Tiramisu"],
    cost_for_two: 400,
    veg_or_nonveg: "Vegetarian",
    tags: ["Pizza", "Italian", "Desserts"],
    image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/079d1a1551619115a435f9b557222464",
  },
  {
    id: 10,
    name: "Seafood Sensations",
    rating: 4.2,
    etp: "Seafood Restaurant",
    menu: ["Grilled Shrimp", "Lobster Bisque", "Fish Tacos", "Key Lime Pie"],
    cost_for_two: 500,
    veg_or_nonveg: "Non-Vegetarian",
    tags: ["Seafood", "Grilled", "Tacos"],
    image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/ff0747ae3755d4ed49a4d7c0c2d8a2d4",
  },
];

export default restdata;
